name: Run tests for GPT-2 inference

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main

jobs:
  test:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout respository
        uses: actions/checkout@v4

      - name: Setup Python
        uses: actions/setup-python@v5
        with:
          python-version: "3.12"

      - name: Setup virtual environmet and install requirements
        run: pip install -r requirements.txt

      - name: Download model weights and configuration
        run: bash download_model.sh

      - name: Run inference tests
        run: pytest